manifests:
  - name: projectA # This should match the project's real name
    type: file
    config:
      # A path to your manifest. This can be either a local path, or a remote
      # path accessible via http(s).
      path: ../projectA/target/manifest.json